name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    strategy:
      fail-fast: false
      matrix:
        python-version: [ "3.11" ]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: poetry

      - name: Install Poetry
        uses: abatilo/actions-poetry@v3
        with:
          poetry-version: "1.8.3"

      - name: Install dependencies
        run: |
          poetry install --no-interaction --no-ansi
          # Ruff & mypy が dev-dependencies に無い場合は↓
          # poetry add --group dev ruff mypy pytest-asyncio --exact

      - name: Ruff lint
        run: poetry run ruff check .

      - name: mypy strict
        run: poetry run mypy .

      - name: Pytest
        run: poetry run pytest -q

      - name: Mark job success
        if: success()
        run: echo "CI passed successfully!"
